/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurfacesRouteImport } from './routes/surfaces'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchemasRouteImport } from './routes/schemas'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GapsRouteImport } from './routes/gaps'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as EndpointsRouteImport } from './routes/endpoints'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidatorsIndexRouteImport } from './routes/validators.index'
import { Route as SudoIndexRouteImport } from './routes/sudo.index'
import { Route as SubnetsIndexRouteImport } from './routes/subnets.index'
import { Route as ProvidersIndexRouteImport } from './routes/providers.index'
import { Route as ExtrinsicsIndexRouteImport } from './routes/extrinsics.index'
import { Route as BlocksIndexRouteImport } from './routes/blocks.index'
import { Route as AdminChangesIndexRouteImport } from './routes/admin-changes.index'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as SubnetsNetuidRouteImport } from './routes/subnets.$netuid'
import { Route as ProvidersSlugRouteImport } from './routes/providers.$slug'
import { Route as ExtrinsicsHashRouteImport } from './routes/extrinsics.$hash'
import { Route as BlocksRefRouteImport } from './routes/blocks.$ref'
import { Route as AccountsSs58RouteImport } from './routes/accounts.$ss58'

const SurfacesRoute = SurfacesRouteImport.update({
  id: '/surfaces',
  path: '/surfaces',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasRoute = SchemasRouteImport.update({
  id: '/schemas',
  path: '/schemas',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsRoute = GapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointsRoute = EndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidatorsIndexRoute = ValidatorsIndexRouteImport.update({
  id: '/validators/',
  path: '/validators/',
  getParentRoute: () => rootRouteImport,
} as any)
const SudoIndexRoute = SudoIndexRouteImport.update({
  id: '/sudo/',
  path: '/sudo/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubnetsIndexRoute = SubnetsIndexRouteImport.update({
  id: '/subnets/',
  path: '/subnets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtrinsicsIndexRoute = ExtrinsicsIndexRouteImport.update({
  id: '/extrinsics/',
  path: '/extrinsics/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksIndexRoute = BlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChangesIndexRoute = AdminChangesIndexRouteImport.update({
  id: '/admin-changes/',
  path: '/admin-changes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubnetsNetuidRoute = SubnetsNetuidRouteImport.update({
  id: '/subnets/$netuid',
  path: '/subnets/$netuid',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersSlugRoute = ProvidersSlugRouteImport.update({
  id: '/providers/$slug',
  path: '/providers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtrinsicsHashRoute = ExtrinsicsHashRouteImport.update({
  id: '/extrinsics/$hash',
  path: '/extrinsics/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRefRoute = BlocksRefRouteImport.update({
  id: '/blocks/$ref',
  path: '/blocks/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsSs58Route = AccountsSs58RouteImport.update({
  id: '/accounts/$ss58',
  path: '/accounts/$ss58',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/endpoints': typeof EndpointsRoute
  '/explorer': typeof ExplorerRoute
  '/gaps': typeof GapsRoute
  '/health': typeof HealthRoute
  '/schemas': typeof SchemasRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/surfaces': typeof SurfacesRoute
  '/accounts/$ss58': typeof AccountsSs58Route
  '/blocks/$ref': typeof BlocksRefRoute
  '/extrinsics/$hash': typeof ExtrinsicsHashRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/subnets/$netuid': typeof SubnetsNetuidRoute
  '/accounts/': typeof AccountsIndexRoute
  '/admin-changes/': typeof AdminChangesIndexRoute
  '/blocks/': typeof BlocksIndexRoute
  '/extrinsics/': typeof ExtrinsicsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/subnets/': typeof SubnetsIndexRoute
  '/sudo/': typeof SudoIndexRoute
  '/validators/': typeof ValidatorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/endpoints': typeof EndpointsRoute
  '/explorer': typeof ExplorerRoute
  '/gaps': typeof GapsRoute
  '/health': typeof HealthRoute
  '/schemas': typeof SchemasRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/surfaces': typeof SurfacesRoute
  '/accounts/$ss58': typeof AccountsSs58Route
  '/blocks/$ref': typeof BlocksRefRoute
  '/extrinsics/$hash': typeof ExtrinsicsHashRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/subnets/$netuid': typeof SubnetsNetuidRoute
  '/accounts': typeof AccountsIndexRoute
  '/admin-changes': typeof AdminChangesIndexRoute
  '/blocks': typeof BlocksIndexRoute
  '/extrinsics': typeof ExtrinsicsIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/subnets': typeof SubnetsIndexRoute
  '/sudo': typeof SudoIndexRoute
  '/validators': typeof ValidatorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/endpoints': typeof EndpointsRoute
  '/explorer': typeof ExplorerRoute
  '/gaps': typeof GapsRoute
  '/health': typeof HealthRoute
  '/schemas': typeof SchemasRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/surfaces': typeof SurfacesRoute
  '/accounts/$ss58': typeof AccountsSs58Route
  '/blocks/$ref': typeof BlocksRefRoute
  '/extrinsics/$hash': typeof ExtrinsicsHashRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/subnets/$netuid': typeof SubnetsNetuidRoute
  '/accounts/': typeof AccountsIndexRoute
  '/admin-changes/': typeof AdminChangesIndexRoute
  '/blocks/': typeof BlocksIndexRoute
  '/extrinsics/': typeof ExtrinsicsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/subnets/': typeof SubnetsIndexRoute
  '/sudo/': typeof SudoIndexRoute
  '/validators/': typeof ValidatorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/endpoints'
    | '/explorer'
    | '/gaps'
    | '/health'
    | '/schemas'
    | '/settings'
    | '/status'
    | '/surfaces'
    | '/accounts/$ss58'
    | '/blocks/$ref'
    | '/extrinsics/$hash'
    | '/providers/$slug'
    | '/subnets/$netuid'
    | '/accounts/'
    | '/admin-changes/'
    | '/blocks/'
    | '/extrinsics/'
    | '/providers/'
    | '/subnets/'
    | '/sudo/'
    | '/validators/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/endpoints'
    | '/explorer'
    | '/gaps'
    | '/health'
    | '/schemas'
    | '/settings'
    | '/status'
    | '/surfaces'
    | '/accounts/$ss58'
    | '/blocks/$ref'
    | '/extrinsics/$hash'
    | '/providers/$slug'
    | '/subnets/$netuid'
    | '/accounts'
    | '/admin-changes'
    | '/blocks'
    | '/extrinsics'
    | '/providers'
    | '/subnets'
    | '/sudo'
    | '/validators'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agents'
    | '/endpoints'
    | '/explorer'
    | '/gaps'
    | '/health'
    | '/schemas'
    | '/settings'
    | '/status'
    | '/surfaces'
    | '/accounts/$ss58'
    | '/blocks/$ref'
    | '/extrinsics/$hash'
    | '/providers/$slug'
    | '/subnets/$netuid'
    | '/accounts/'
    | '/admin-changes/'
    | '/blocks/'
    | '/extrinsics/'
    | '/providers/'
    | '/subnets/'
    | '/sudo/'
    | '/validators/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  EndpointsRoute: typeof EndpointsRoute
  ExplorerRoute: typeof ExplorerRoute
  GapsRoute: typeof GapsRoute
  HealthRoute: typeof HealthRoute
  SchemasRoute: typeof SchemasRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  SurfacesRoute: typeof SurfacesRoute
  AccountsSs58Route: typeof AccountsSs58Route
  BlocksRefRoute: typeof BlocksRefRoute
  ExtrinsicsHashRoute: typeof ExtrinsicsHashRoute
  ProvidersSlugRoute: typeof ProvidersSlugRoute
  SubnetsNetuidRoute: typeof SubnetsNetuidRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  AdminChangesIndexRoute: typeof AdminChangesIndexRoute
  BlocksIndexRoute: typeof BlocksIndexRoute
  ExtrinsicsIndexRoute: typeof ExtrinsicsIndexRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  SubnetsIndexRoute: typeof SubnetsIndexRoute
  SudoIndexRoute: typeof SudoIndexRoute
  ValidatorsIndexRoute: typeof ValidatorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surfaces': {
      id: '/surfaces'
      path: '/surfaces'
      fullPath: '/surfaces'
      preLoaderRoute: typeof SurfacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas': {
      id: '/schemas'
      path: '/schemas'
      fullPath: '/schemas'
      preLoaderRoute: typeof SchemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps': {
      id: '/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof GapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints': {
      id: '/endpoints'
      path: '/endpoints'
      fullPath: '/endpoints'
      preLoaderRoute: typeof EndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validators/': {
      id: '/validators/'
      path: '/validators'
      fullPath: '/validators/'
      preLoaderRoute: typeof ValidatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sudo/': {
      id: '/sudo/'
      path: '/sudo'
      fullPath: '/sudo/'
      preLoaderRoute: typeof SudoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subnets/': {
      id: '/subnets/'
      path: '/subnets'
      fullPath: '/subnets/'
      preLoaderRoute: typeof SubnetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrinsics/': {
      id: '/extrinsics/'
      path: '/extrinsics'
      fullPath: '/extrinsics/'
      preLoaderRoute: typeof ExtrinsicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/blocks'
      fullPath: '/blocks/'
      preLoaderRoute: typeof BlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-changes/': {
      id: '/admin-changes/'
      path: '/admin-changes'
      fullPath: '/admin-changes/'
      preLoaderRoute: typeof AdminChangesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subnets/$netuid': {
      id: '/subnets/$netuid'
      path: '/subnets/$netuid'
      fullPath: '/subnets/$netuid'
      preLoaderRoute: typeof SubnetsNetuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$slug': {
      id: '/providers/$slug'
      path: '/providers/$slug'
      fullPath: '/providers/$slug'
      preLoaderRoute: typeof ProvidersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrinsics/$hash': {
      id: '/extrinsics/$hash'
      path: '/extrinsics/$hash'
      fullPath: '/extrinsics/$hash'
      preLoaderRoute: typeof ExtrinsicsHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/$ref': {
      id: '/blocks/$ref'
      path: '/blocks/$ref'
      fullPath: '/blocks/$ref'
      preLoaderRoute: typeof BlocksRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$ss58': {
      id: '/accounts/$ss58'
      path: '/accounts/$ss58'
      fullPath: '/accounts/$ss58'
      preLoaderRoute: typeof AccountsSs58RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  EndpointsRoute: EndpointsRoute,
  ExplorerRoute: ExplorerRoute,
  GapsRoute: GapsRoute,
  HealthRoute: HealthRoute,
  SchemasRoute: SchemasRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  SurfacesRoute: SurfacesRoute,
  AccountsSs58Route: AccountsSs58Route,
  BlocksRefRoute: BlocksRefRoute,
  ExtrinsicsHashRoute: ExtrinsicsHashRoute,
  ProvidersSlugRoute: ProvidersSlugRoute,
  SubnetsNetuidRoute: SubnetsNetuidRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  AdminChangesIndexRoute: AdminChangesIndexRoute,
  BlocksIndexRoute: BlocksIndexRoute,
  ExtrinsicsIndexRoute: ExtrinsicsIndexRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  SubnetsIndexRoute: SubnetsIndexRoute,
  SudoIndexRoute: SudoIndexRoute,
  ValidatorsIndexRoute: ValidatorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
